# Generated by Django 5.2.17 on 2026-09-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supplementcategory_supplementproduct_supplementsale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
