# Generated by Django 5.2.17 on 2026-09-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_member_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Debit / Credit Card'), ('BANK_TRANSFER', 'Bank Transfer / NEFT')], default='UPI', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplementsale',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Credit / Debit Card'), ('NETBANKING', 'Net Banking / Transfer')], default='UPI', max_length=20),
        ),
    ]
