# Generated by Django 5.2.17 on 2026-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expensecategory_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
