# Generated by Django 5.2.17 on 2026-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
