# Generated by Django 5.2.17 on 2026-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sync_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
