# Generated by Django 5.2.17 on 2026-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_member_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('WEIGHT_TRAINING', 'Weight Training'), ('CARDIO', 'Weight Training + Cardio'), ('GENERAL', 'General')], default='WEIGHT_TRAINING', max_length=30),
        ),
    ]
