# Generated by Django 5.2.17 on 2026-09-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_membershipplan_plan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
    ]
