# Generated by Django 5.2.17 on 2026-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementsale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplementsale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('PENDING', 'Pending Payment')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='supplementsale',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
