# Generated by Django 5.2.17 on 2026-09-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_supplementsale_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementsale',
            name='initial_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
