# Generated by Django 5.2.17 on 2026-09-06 17:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_supplementsale_initial_paid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Debit / Credit Card'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('NET_BANKING', 'Net Banking')], default='UPI', max_length=30)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.supplementsale')),
            ],
            options={
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
